block.settings.whitelabel_search_block:
  type: block_settings
  label: 'OE Whitelabel search block'
  mapping:
    form:
      type: mapping
      label: 'Form'
      mapping:
        action:
          type: string
          label: 'Action'
          translatable: true
        region:
          type: string
          label: 'Region'
          translatable: true
    input:
      type: mapping
      label: 'Input'
      mapping:
        name:
          type: string
          label: 'Name'
          translatable: true
        label:
          type: string
          label: 'Label'
          translatable: true
        placeholder:
          type: string
          label: 'Placeholder'
          translatable: true
    button:
      type: mapping
      label: 'Button'
      mapping:
        label:
          type: string
          label: 'Button label'
          translatable: true
    view_options:
      type: mapping
      label: 'View Options'
      mapping:
        enable_autocomplete:
          type: boolean
          label: 'Enable autocomplete'
        id:
          type: string
          label: 'View id'
        display:
          type: string
          label: 'View display'
