field.formatter.settings.oe_whitelabel_helper_address_inline:
  type: mapping
  label: 'Address inline formatter settings'
  mapping:
    delimiter:
      type: string
      label: 'Delimiter for address items.'
condition.plugin.oe_whitelabel_helper_current_component_library:
  type: condition.plugin
  mapping:
    component_library:
      type: string
